local GSE = GSE
local Statics = GSE.Static

Statics.Patrons = {
    "'William Meringolo",
    "900obzen ",
    "A Four",
    "AJ Guckian",
    "ARTEX",
    "Aaron Smith",
    "Aaron Steley",
    "Abnerdoon",
    "Adaestra ",
    "Adam Anderson",
    "Adam Doherty",
    "Adam Fisher",
    "Adam Tall",
    "Adrian Maier",
    "Adventures Of Raven",
    "Aiden Gramson",
    "Akk",
    "Alejandro Sanclemente",
    "Alex",
    "Allan Korsgaard",
    "Allan Smith Nielsen",
    "Allen Ampueda",
    "Andre Carbonell",
    "Andrew Baldwin",
    "Andrew Fox",
    "Andrew Lester",
    "Andrew VanArman",
    "Andris Kulmans",
    "Andy Erickson",
    "Angel Marchini",
    "Angrypug",
    "Anthony",
    "Anthony Lutke",
    "Anubikk ",
    "Arne Krüger",
    "Ashley",
    "Ashley Ludwig",
    "Ashneel Kumar",
    "Axellis ",
    "BRIAN V DELLER",
    "Badcat",
    "Baely ",
    "Baka Pixel",
    "Bearded_Gamer ",
    "Ben Hocking",
    "Bengt Grahl",
    "Bennyfof",
    "Beta",
    "Bghy Rbfch",
    "BigPoppaRich",
    "Billy ",
    "Binary Nick",
    "Bob",
    "Brandon Bks",
    "Brandon Conklin",
    "Brett Warfle",
    "Brian",
    "Brian Dickerson",
    "Brian Lewin",
    "Brian Lynch",
    "Brian Miller",
    "Bromdor",
    "Bryan Burns",
    "Bryan Ingram",
    "Bryan Seitz",
    "Caleb",
    "Calvin Jones",
    "Carter Cross",
    "Charles",
    "Charles R Tabor",
    "Chase Hoppock",
    "Choco Munday",
    "Chris Bunting",
    "Chris Cordwell",
    "Chris Esparza",
    "Chris G",
    "Chris Jackson",
    "Chris Juengel",
    "Chris Livingston",
    "Christian Mostert",
    "Christopher Lee",
    "Christopher Young",
    "Christos ",
    "Codda Matl",
    "Colm",
    "Corey Marchant",
    "Cruelier",
    "Crystal Gator",
    "DENNIS CHRISTENSEN",
    "DJ",
    "DJ_FingaGunz",
    "DMFerree",
    "Damon Walker",
    "Dan",
    "Dan Inda",
    "Daniel Kristofersson",
    "Daniel Perez",
    "Daniel Sümmchen",
    "Daniel Thomas",
    "David Isburgh",
    "David Rice",
    "David Rose",
    "David Thrower",
    "Deborah Gough",
    "Deezyl Fizzlepop",
    "Denis Samoilov",
    "Dennis Jakobsen",
    "Diedora",
    "Dieter Cazon",
    "Dirty Apparition",
    "Dominik Krabacher",
    "Dredd",
    "Drioz",
    "Dustin Davenport",
    "Dustin Gadd",
    "Dustin W",
    "E Peters",
    "Edgar Dazevedo",
    "Eduard Claassen",
    "Elange4 ",
    "Elfyau",
    "Eli Sapanayev",
    "Emanuel Barbi",
    "Emo Mihov",
    "Enmity",
    "Eric Desmarais",
    "Eric Donini",
    "Eric Rainey",
    "Eric Roberts",
    "Eric Sanders",
    "Eric Stoeckel Jr",
    "Eric Vasquez",
    "Eric Vincent",
    "Eric donini",
    "Erin Reymann",
    "Ernest Dolby",
    "Euben Hadd",
    "Eusélie",
    "Everett St.Clair",
    "Evie McAdoo",
    "Excutive Outcome game",
    "Eznoda",
    "FERDIN GONZALEZ",
    "FPSMarcus",
    "FUT_Sovereign ",
    "Fadi Alfadda",
    "Fallens Death",
    "Fangorian_1337",
    "Ferat A",
    "Florin Enache",
    "FyuZ. ",
    "GamingMama55",
    "Gary",
    "Gary Markland",
    "Gendi",
    "Geoffrey Tang",
    "George McCubbins",
    "Gerald McCandless",
    "Gianluca Berian",
    "Gilian Bentulan",
    "Glenn van Kooijk",
    "Goregoth",
    "Greg Schmitz",
    "Gregory M",
    "Grumpy British old Gamer",
    "Gustav Gans",
    "Gấu Panda",
    "Hannah Mae",
    "Hansli Peterli",
    "Henrik Nielsen",
    "Herbert Besenfelder",
    "Holger",
    "Holli Mcmillen",
    "Hollis Ford",
    "Hugh Judd",
    "Isaiah Lombardy",
    "Ivan Chiu",
    "J G",
    "Jacek Pasławski",
    "Jack Selektion",
    "Jacob Richey",
    "Jakob Andersen",
    "James Beck",
    "James Blamey",
    "James Faircloth",
    "James Turnbull",
    "Jamie Cuomo",
    "Jamie Currier",
    "Jani Kay",
    "Jason ",
    "Jason Cartledge",
    "Jason Johnson",
    "Jason Kartes",
    "Jasper Hengefeld",
    "Jean-Philippe Baril",
    "Jed Lawton",
    "Jeff Berman",
    "Jeff Butler",
    "Jeff Hughes",
    "Jeffrey White",
    "Jennifer Angelidis",
    "Jeremy Grayson",
    "Jeremy Harvey",
    "Jeremy Jones",
    "Jeremy Neumann",
    "Jerrod Linderman",
    "Jerry T",
    "Jessica",
    "Jim",
    "Jim B",
    "Jinazz",
    "Jodi Meese",
    "Joe Davis",
    "Joel D Bailey",
    "Johan Andersson",
    "Johan Lindqvist",
    "John Beland",
    "John D Aulbu",
    "John Martin",
    "John smith",
    "Jon Noland",
    "Jon Waalewyn",
    "Jonathan Devore Scales",
    "Jonathon Finlay",
    "Joseph Lowery",
    "Josh Silvia",
    "Joshua Stevens",
    "José Carlos Pérez Carreño",
    "Junior Rodriguez",
    "KURT MOSS",
    "Kal basra",
    "Karl gregory",
    "Karoldue ",
    "Keith Fults",
    "Keith Kelly",
    "Kelly Morehead",
    "Kemal Tolun",
    "Ken McCune",
    "Kenny Pritchard",
    "Kevin Fellion",
    "Kevin Hare",
    "Kevin Ibrahim",
    "Kevin James",
    "Kevin Kuijer",
    "Khoa Truong",
    "Kickn Chickn",
    "Kiel Arenas",
    "Klaus Dobrzynski",
    "Kourosh Vosough",
    "Kristin Bateman",
    "Kristopher Bowling",
    "Kyle Francis",
    "Lara Marcattili",
    "Larry Hook",
    "Lars Wingemark",
    "Laura A Clegg",
    "Laura Sieloff",
    "Laurie Holmes",
    "Leprona",
    "LivinOnTheCorner",
    "Luis Flores",
    "Luke Beals",
    "Luke Newland",
    "MVP",
    "Macroholic",
    "Magnerian",
    "Mals",
    "Manuel Nordmeier",
    "Marc allen",
    "Marco Petraszczuk",
    "Marcus Andesson",
    "Mardy Stevens",
    "Marek Dvořák",
    "Mark",
    "Mark ",
    "Mark Bradley",
    "Mark Robinson",
    "Mark van de Beek",
    "Marshmellow",
    "Martin Needham",
    "Martin Needham",
    "Martin Vines",
    "Mathusala",
    "Matthew Jenner",
    "Melchy",
    "Melissa N Anderson",
    "Melissa condon",
    "Meph",
    "Mephchens",
    "Mephiroth",
    "Mercurio",
    "Michael",
    "Michael Bailey",
    "Michael Brodie",
    "Michael Irving",
    "Michael Mcdaniels",
    "Michael R Kauffmann",
    "Michael Schulz",
    "Michael Swancott",
    "Michal Stalanowski",
    "Miethos",
    "Mike Pegg",
    "Mikkel Juul Jørgensen",
    "Misty Jinn",
    "Mitchell Emberson",
    "MolarMacros",
    "Nancy Pierson",
    "Naomi McMillan",
    "Nathan Jetson",
    "Nathan Warfield",
    "Nebiros",
    "Neil C",
    "Nicholas Brown",
    "Nimmerland Gaming [NlG] Brainz",
    "Nora Kirschling",
    "NotSure SureNot",
    "Oliver Berger",
    "Orion8 Junk",
    "Ouya France",
    "Ozzi",
    "Papa Midnite",
    "Patrick Lüke",
    "Patrick O'Hagan",
    "Paul Guertin",
    "Paul Kingman",
    "Penny2",
    "Peter Haugen",
    "Peter McNinch",
    "Peter von der Ahe",
    "Petter Zweidorff",
    "Phat Le",
    "Phil ",
    "Pierre Hundt",
    "Pippa Martel",
    "Possum Jenkins",
    "RACHEL liperote",
    "Radioactive Bullfrog",
    "Rakuza yoknomu",
    "Randall Crank",
    "Randy Barton",
    "Randy G",
    "Randy Rushing",
    "Ray Adams",
    "Ray Feliciano",
    "Raymond Monk",
    "Razerwing",
    "Rebecca Gosdin",
    "Renato Freitas",
    "Rene Traue",
    "René Madl",
    "Rhaina",
    "Ricky Woods",
    "Robert Costello",
    "Robert Harris",
    "Robert Mcknight",
    "Robert Pipan",
    "Robert Wears",
    "Robert Webb",
    "Roberto Roeschmann",
    "Roberto Zanini",
    "Robin Laubinger",
    "Rody z",
    "Roger Heiniluoma",
    "Rolandas Normanas",
    "RoleClass ",
    "Ronald De Martines",
    "Ronnie Otterborg",
    "Russell Baker",
    "Ryan ",
    "Ryan Hickey",
    "Ryo",
    "S Driggers",
    "Samma",
    "Samuel Lacerda",
    "Samuel Spencer",
    "Sandra Primm",
    "Sandy (AKA SassyGamer)",
    "Scarlett Knight",
    "ScaryLarryGames",
    "Schiwouna Schi",
    "Scott Davis",
    "Scott Flippo",
    "Scott Hounsell",
    "Scott Penney",
    "Scott Rose",
    "Scotty",
    "Sean-Heidi Serraguard",
    "Sebastian Kieback",
    "Sergey Droba",
    "ShadyLucifer ",
    "Shane Kuchler",
    "Shaun Baxter",
    "Shaun Flagel",
    "Shelltoekicks",
    "Shtev",
    "Sid Robichaud",
    "Simon Karlskov",
    "Simon Wilcock",
    "Sol LeTaire",
    "Solltex ",
    "Sparrowhawk Sr",
    "Spencer Blomquist",
    "Stefan Hauck",
    "Stefano Filardo",
    "Stephen Seagrave",
    "Sternwind",
    "Steve Clink",
    "Steve Hensch",
    "Steven Hansen",
    "Steven Shaw",
    "Stew Frei",
    "Stuart Hendrie",
    "Supbear ",
    "Susan Mushill",
    "Susan Mushill",
    "Sydney",
    "T D",
    "Tabby Post",
    "Tad Oleson",
    "Tamer Baes",
    "Tawaporah",
    "The world through my eyes",
    "Thomas Maurdal",
    "Thomas Nicholson",
    "Thomas Rambaut",
    "Thore Kvalheim",
    "Thorn the Fox",
    "Tiegars",
    "Tim Firth",
    "Tim Weiden",
    "Timothy Campbell",
    "Tituswolfe",
    "Tom Straugh",
    "Tommy ",
    "Tommy Southam",
    "Tommy White",
    "Torbjörn Jönsson",
    "Toril Harink ",
    "Toto Leo",
    "Tracy Howard",
    "Travis Delaney",
    "Tris",
    "Troy Rooker",
    "Truzedo ",
    "Tsaiko",
    "TwistedSMF ",
    "TwiztidBloom",
    "UhohOreo ",
    "Unktehila Iksar",
    "Venni Liimatainen",
    "Victor Hodges",
    "Vince Orlando",
    "W Wilson",
    "Walter Beiter",
    "Warren Jumper",
    "William Kelley",
    "William Lee",
    "William P Grady",
    "William Sharp",
    "William Smith",
    "Windfey",
    "Wizard Hayden",
    "Woo Kim",
    "Zane Savage",
    "Zoonets",
    "adam humphreys",
    "alan coutts",
    "ale diki",
    "beat theory",
    "bk",
    "chris ogle",
    "cloutyTV ",
    "crystaltech",
    "csaba jani cimpan",
    "curtis buffum",
    "david hawke",
    "devlik",
    "evasion",
    "ffcjonny",
    "friedbones",
    "giorgino",
    "impaxx ",
    "james hyatt",
    "jamie bradley",
    "jay garcia",
    "jean-marie rossi",
    "joe faultless",
    "kay rennow",
    "kelly jarrell",
    "kristian montevecchi",
    "lloyd spencer",
    "luc janssens",
    "manuel Leistner",
    "mike sano",
    "mike saul",
    "mourad abrahim",
    "mr mods",
    "neofodder",
    "pantinhatv",
    "pascalmaramis",
    "patrice heinemann",
    "paytun",
    "quoc nguyen",
    "ralf heckel",
    "rightonetwo",
    "ryan kloepper",
    "sten",
    "stiph curry",
    "ttplank",
    "twmwalters",
    "wouZAR ",
    "wynne clark",
    "xManiac",
    "xan2622",
    "zibiken",
    "Александр Кузьмин",
    "熙 凌"
}